name: Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Dependencies
      run: |
        sudo apt-get install cbp2make libxtst-dev libxext-dev yasm

    - name: Build FFmpeg
      run: |
        git clone --depth 1 --branch n4.2.1  git://source.ffmpeg.org/ffmpeg
        cd ffmpeg
        ./configure --disable-everything --enable-encoder=mpeg1video --disable-shared --disable-hwaccels --disable-autodetect --enable-muxer=mpegts --prefix=../source/linux/ffmpeg/
        make
        make install

    - name: Build LWS
      run: |
        git clone --depth 1 --branch v3.2-stable https://github.com/warmcat/libwebsockets
        cd libwebsockets
        mkdir build
        cd build
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -D LWS_WITH_SSL=OFF -D LWS_WITHOUT_TESTAPPS=ON -D LWS_WITH_SHARED=OFF -D LWS_WITH_STATIC=ON -D CMAKE_INSTALL_PREFIX=../../source/linux/libwebsockets ..
        make install
        
    - name: Prepare Linux Development 
      run: | 
        cd source/linux
        zip -r ../../linux-development.zip ffmpeg libwebsockets

    - name: Upload Linux Development
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./linux-development.zip
        asset_name: linux-development.zip
        tag: autobuild
        overwrite: true 
        
    - name: Build JSMpeg-VNC
      run: |
        cd project/
        cbp2make -in jsmpeg-vnc.cbp -out makefile -targets linux
        make -f makefile

    - name: Prepare Release Asset
      run: | 
        cd bin 
        zip ../jsmpeg-vnc-linux.zip jsmpeg-vnc client client/index.html client/jsmpeg.min.js client/jsmpeg-vnc.js

    - name: Upload Release Asset
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./jsmpeg-vnc-linux.zip
        asset_name: jsmpeg-vnc-linux.zip
        tag: autobuild
        overwrite: true